---
title: "text"
output: html_document
date: "2023-11-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Intro

Transplant forcast for patients on liver transplant waiting list: An bayesian regression model analysis

To ensure the success of liver transplantation for patients awaiting liver transplants, various factors must be carefully considered. Among these, the availability of a suitable donor liver and compatibility in blood type emerge as critical factors. In a study conducted by Kim, W. Ray, et al. (2006), time until event (transplant, death or withdrawal from list) were modeled and examined. The study compared the modeling efficacy between competing risk analysis based on Cox-proportional hazard models and the previously frequently used Kaplan-Meier modeling, which proved less adept.

Kim, W. Ray, et al. demonstrated that Cox-proportional hazard models exhibited higher accuracy in estimating the mortality among individuals awaiting liver transplantation.

This project aims to estimate the probabilities of each outcome (transplant, death, withdrawal) with the help of the predictors age, sex, year entered and blood type with bayesian regression models (brm). This is an inherently different approach than that of Kim et al., as theirs estimates the time until an event occurs, and the brm estimates a binary/categorial\*\* outcome (the event occuring).

\*\***confirm that true**

This project uses the data obtained from the Kim et al. study, which reflects the transplant experience in the Mayo Clinic in Rochester spanning over a ten year period during the 1990's. A more detailed description is depicted in table 1 below.

The data is historically accurate and informative, but since transplant allocation policies might have changed since the ninties, it might not accurately describe the situation today. However, the problem of liver shortage remains.

Table 1. Description of the data set.

| Variable |   Type    |                                  Description                                  |
|:---------------:|:---------------:|:------------------------------------:|
|   age    |    int    |                       age of entering the waiting list                        |
|   sex    | character |                            male (m) or female (f)                             |
|   abo    | character |                            blood type: A, B, AB, O                            |
|   year   |    int    |                         year of entering waiting list                         |
|  futime  |    int    |                     time from entry until event, in days                      |
|  event   | character | final disposition: censored, death, ltx (transplant) or withdraw (from study) |


